### ISSUE TITLE
avr/power.h library download

### ISSUE THREAD

**Issue by matpi** [Synapseware/avr#4]
Hi, 

I would like to download <avr/power.h> library and use it in one arduino project. In your GitHub, there is no option for clone or download  this library. I can't use the "find file or copy path" option to download arduino libraries... I have used to download and unzip the zip-file, and move the library folder to arduino libraries folder. Is it possible for you to add this kind of option for downloading the <avr/power.h> library ... 

Best Regards, matpi

**Comment by dachew** [comment]
Hi Matpi - this is a personal backup of the avr-libc code.  I'd suggest you just install the latest from the official sources.  I will close this repo as it's deprecated.
